version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build:
      context: ./
      dockerfile: flaskr/Dockerfile
    volumes:
      - /Proyecto-Grupo20-202120:/usr/src/flaskr
    ports:
      - "8085:8085"
    command: gunicorn --bind 0.0.0.0:8085 flaskr.app:app
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
